### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by ploner** [mhnierhoff/R-marketing-analysis-packages#3]
Hi, I am the maintainer of the package RMixpanel. The link to the site has changed from https://github.com/7factory/RMixpanel to https://github.com/ploner/RMixpanel - already some years ago.
Would be nice to update it - thanks, Meinhard

**Comment by ploner** [comment]
The link is still broken...

**Comment by mhnierhoff** [comment]
Thanks for the hint and sorry for the delay - link is now fixed.
